language: node_js
node_js:
  - "10"
  - "9"
  - "8"

stages:
  - test
  - lint

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: test
      script: npm run test:unit
    - stage: lint
      node_js: "10"
      script: npm run lint
