language: node_js

stages:
  - name: typecheck-test-lint
    if: branch = master OR type IN (pull_request)
  - name: deploy-npm
    if: tag IS present
  - name: deploy-website
    if: branch = master AND NOT type IN (pull_request)

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: typecheck-test-lint
      name: typecheck
      node_js: '8'
      script: npm run typecheck

    - stage: typecheck-test-lint
      name: test
      node_js: '10'
      script: npm run test:unit
    - stage: typecheck-test-lint
      name: test
      node_js: '9'
      script: npm run test:unit
    - stage: typecheck-test-lint
      name: test
      node_js: '8'
      script: npm run test:unit

    - stage: typecheck-test-lint
      name: lint
      node_js: '8'
      script: npm run lint

    - stage: deploy-npm
      node_js: '8'
      script: skip
      deploy:
        provider: script
        script: bash publish.sh
        skip_cleanup: true
        on:
          tags: true

    - stage: deploy-website
      node_js: '8'
      before_install: cd website
      script: npm run build
      deploy:
        provider: pages
        local-dir: website/dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
