language: node_js

stages:
  - test
  - lint

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: test
      node_js: "10"
      script: npm run test:unit
    - stage: test
      node_js: "9"
      script: npm run test:unit
    - stage: test
      node_js: "8"
      script: npm run test:unit
    - stage: lint
      node_js: "8"
      script: npm run lint

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    node: "8"
