language: node_js

stages:
  - test
  - lint
  - name: deploy
    if: tag IS present
  - name: deploy-website
    if: branch = master


cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: test
      node_js: "10"
      script: npm run test:unit
    - stage: test
      node_js: "9"
      script: npm run test:unit
    - stage: test
      node_js: "8"
      script: npm run test:unit

    - stage: lint
      node_js: "8"
      script: npm run lint

    - stage: deploy
      node_js: "8"
      script: skip
      deploy:
        provider: script
        script: bash publish.sh
        skip_cleanup: true
        on:
          tags: true
      # before_deploy:
        # - npm version --no-git-tag-version "$TRAVIS_TAG"
        # - npm run build
        # - cd lib
      # deploy:
        # - provider: npm
          # skip_cleanup: true
          # email: $NPM_EMAIL
          # api_key: $NPM_AUTH_TOKEN
          # on:
            # tags: true
        # - provider: script
          # skip_cleanup: true
          # script:
            # cd ..
            # && git checkout -b master
            # && git add package.json package-lock.json
            # && git commit --message "$TRAVIS_TAG"
            # && git remote add deploy https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
            # && git push deploy master
          # on:
            # tags: true

    - stage: deploy-website
      node_js: "8"
      before_install: cd website
      script: npm run build
      deploy:
        provider: pages
        local-dir: website/dist
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
