name: Node CI

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest]

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci --no-audit
    - run: npm run build
    - run: npm run test

    - run: npm run test:coverage
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '12'
    - name: send coverage report
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '12'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
  coverage:
    runs-on: ubuntu-latest

# TODO add a 'test published package script'
