name: NPM Publish

on:
  release:
    types: [published, created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
##############################
#           Test             #
##############################
    - run: npm ci --no-audit
    - run: npm run build
    - run: npm run test
##############################
#       NPM Publish          #
##############################
    - name: npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.github_token }}
        TAG: ${{ github.ref }}
      run: |
        npm version --no-git-tag-version $TAG
        cd lib
        echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > .npmrc
        npm publish
        cd ..
        git fetch origin master
        git checkout master
        git add package.json package-lock.json
        git commit --message "release $TAG"
        git remote add deploy https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        git push deploy master
