name: NPM Publish

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
##############################
#           Test             #
##############################
    - run: npm ci --no-audit
    - run: npm run build
    - run: npm run test
##############################
#       NPM Publish          #
##############################
    - name: npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_PUSH_ACCESS_TOKEN }}
        TAG: ${{ github.event.release.tag_name }}
      run: |
        npm version --no-git-tag-version $TAG
        npm run build
        cd lib
        echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > .npmrc
        npm publish
        cd ..
    - name: bump package version on origin/master
      uses: github-actions-x/commit@v2.1
      with:
        github-token: ${{ secrets.GITHUB_PUSH_ACCESS_TOKEN }}
        commit-message: release ${{  github.event.release.tag_name }}
